# Numpy Operations

In [ ]:
#Array with Array operations
#Array with Scalar operations
#Universal array functions - mathematical operations

In [ ]:
#Array with Array operations

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr/arr

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#Note that in the above case of array division, for the first element in the array i.e., 0/0, numpy does not give an 
#error. Instead it gives a warning and prints the output.

In [ ]:
#In case of Python, there would be error for this operation

In [12]:
2/0

ZeroDivisionError: division by zero

In [ ]:
#Array with scalar operations

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [10]:
arr*100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [11]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [13]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
#Universal array functions are available @ https://numpy.org/doc/stable/reference/ufuncs.html