# numpy array in Python

In [ ]:
#They are 2 types, 1D arrays called Vectors and 2D arrays called Matrices
#Numpy arrays are used to convert Python objects into Vectors and Matrices
#For ex let us see with the object list

In [2]:
lst=[1,2,3]

In [2]:
import numpy as np

In [5]:
arr=np.array(lst)

In [6]:
arr

array([1, 2, 3])

In [7]:
lst2=[[1,2],[3,4],[5,6]]

In [8]:
arr2 = np.array(lst2)

In [9]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Numpy inbuilt functions

In [ ]:
#Usually we use numpy's inbuilt functions to generate arrays
#arange is one of them and the first we are going to see
#np.arange

In [ ]:
#1.

In [13]:
#This one is similar to Python's range. It generates integers as per the start and end specified.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#Third arg here is the step. It generates integers as per the specified start and end, with a step interval of 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
#2.

In [ ]:
#Another numpy inbuilt function is zeros. This helps in generating 1D or 2D numpy arrays of zeros
#np.zeros

In [16]:
#Below returns single dimension array of 4 zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
#For 2D we can pass a tuple to zeros()
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#The above is 2D array (matrix) of zeros with 3 rows and 4 columns

In [ ]:
#3.

In [ ]:
#Another inbuilt function is ones
#np.ones

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#4.

In [3]:
#Another inbuilt function is linspace
#np.linspace
#It generates evenly spaced numbers over the specified interval (third arg). Here, third arg is used to 
#specify num of points bw start and end.
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [ ]:
#5.

In [ ]:
#Identity matrix is a 2D square matrix, i.e., no of rows=no of cols and the diagonal is all 1s
#Ex

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#6.np.random.

In [ ]:
#numpy can be used to generate random numbers using np.random
#Again np.random has various methods in itself. Let us use rand()
#If a single number is passed it generates a 1D array of size the passed number

In [5]:
np.random.rand(5)#generates 5 random numbers between 0 to 1

array([0.4784544 , 0.21048438, 0.60259432, 0.47935106, 0.85305633])

In [ ]:
#For a 2D array of random numbers

In [6]:
np.random.rand(4,5)

array([[0.56817857, 0.74642225, 0.79434479, 0.67693466, 0.09272311],
       [0.13090539, 0.91510871, 0.33984702, 0.98406809, 0.13407299],
       [0.4855872 , 0.21602459, 0.43208608, 0.70727764, 0.6899259 ],
       [0.7358619 , 0.85759875, 0.19197029, 0.23738188, 0.41798613]])

In [ ]:
#If you want random numbers to be generated from Standard distribution use randn() 
#i.e., random numbers generated around 0

In [7]:
np.random.randn(5)

array([-3.34343589,  0.58991425,  0.50630944,  0.10764553,  0.13038823])

In [ ]:
#If you want random integers to be generated between specified values (start and end index) use randint
#The below generates random integer between 1 and 100, inclusive of 1 and exclusive of 100

In [13]:
np.random.randint(1,100)

23

In [ ]:
#Also, a 3rd arg could be passed to randint and that is number of random integers to be returned
#Ex below generates 10 random integers

In [12]:
arr=np.random.randint(1,100,10)

In [14]:
arr

array([96, 31, 47, 47, 23, 51, 92, 21, 33, 96])

In [ ]:
#There is a reshape method that allows you to reshape an existing array

In [17]:
arr.reshape(5,2)

array([[96, 31],
       [47, 47],
       [23, 51],
       [92, 21],
       [33, 96]])

In [18]:
arr.max()

96

In [19]:
arr.min()

21

In [25]:
arr=arr.reshape(10)

In [26]:
arr

array([96, 31, 47, 47, 23, 51, 92, 21, 33, 96])

In [ ]:
#Blow returns index of max element

In [27]:
arr.argmax() 

0

In [28]:
arr.argmin()

7

In [ ]:
#Blow returns shape of the array

In [33]:
arr.shape

(10,)

In [ ]:
#10, above, indicates that the shape of the array is 1D vector

In [ ]:
#Blow is used to find the datatype of the array

In [35]:
arr.dtype

dtype('int64')

# Numpy Indexing and Selection