# Numpy Indexing and Selection

In [ ]:
#Numpy Indexing is similar to Python Indexing (slicing)

In [3]:
import numpy as np

In [8]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Let us select the element with value 5

In [6]:
arr[5]

5

In [9]:
arr[6]

6

In [ ]:
#Let us say, we want to select a range of elements

In [10]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [11]:
#Let us say, we want to grab everything beyond index 5

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
#Until here the behavior of Numpy arrays was similar to Python Lists. The feature that makes it unique is their
#ability to broadcast
#For ex blow we are broadcasting values of elements 0 to 3 in arr to be equal to 100

In [14]:
arr[0:4]=100

In [15]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [16]:
arr[5:]=200

In [17]:
arr

array([100, 100, 100, 100,   4, 200, 200, 200, 200, 200, 200])

In [ ]:
#An important concept below

In [22]:
array=np.arange(0,11)

In [23]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slice_of_array=array[:5]

In [25]:
slice_of_array

array([0, 1, 2, 3, 4])

In [ ]:
#Let us broadcast the slice_of_array to 200

In [36]:
slice_of_array[:]=200

In [37]:
slice_of_array

array([200, 200, 200, 200, 200])

In [28]:
array

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [ ]:
#In order to create a copy we need to specifically use the copy method, as below

In [29]:
array_copy=array.copy()

In [30]:
array

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [31]:
array_copy

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [32]:
array_copy[:]=99

In [33]:
array_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [34]:
array

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [ ]:
#Here array and array_copy are 2 different copies

# Indexing a 2D array

In [ ]:
#Let us generate a 2D array

In [4]:
array=np.array([[1,2,3],[4,5,6]])

In [5]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
array[0,1]

2

In [7]:
array[1,2]

6

In [8]:
array[:1]

array([[1, 2, 3]])

In [ ]:
#Conditional selection from array

In [9]:
arr=np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Splitting array based on conditional select

In [12]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [ ]:
#Create a 2d array and do slicing - selecting a portion of the array

In [16]:
arr2d = np.arange(50).reshape(5,10)

In [17]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#grab 13,14,23,24

In [19]:
arr2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [ ]:
#grab 35,36,45,46

In [21]:
arr2d[3:5,5:7]

array([[35, 36],
       [45, 46]])